version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./:/var/www
    working_dir: /var/www
    ports:
      - "127.0.0.1:8030:80"
    environment:
      - NGINX_PORT=80
    restart: unless-stopped
    links:
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    restart: unless-stopped